# Generated by Django 2.0.2 on 2018-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180218_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_action',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
